# Dependencies
markdown:            redcarpet
highlighter:         pygments
redcarpet:
  extensions: ["fenced_code_blocks", "autolink", "tables"]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Colin the Geek
description:         The thoughts, ideas and musings of a full-stack software developer.
url:                 http://colinthegeek.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Colin Orr

# Custom vars
version:             1.0.0
