# Dependencies
markdown:            kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Colin the Geek
description:         The thoughts, ideas and musings of a full-stack software developer.
url:                 http://colinthegeek.com
baseurl:             /
paginate:            5
gems:                [jekyll-paginate]

# About/contact
author:
  name:              Colin Orr

# Custom vars
version:             1.0.0
